environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      
matrix:
    fast_finish: true

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  
platform:
    - x64
    
install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip
  - pip install numpy scipy atomneb nose
  - pip install coverage

build_script:
  - python setup.py install"

test_script:
  - nosetests
